import Head from 'next/head';

export default function Header({ title }) {
    return (
        <Head>
            <title>{title} | Next Movies</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}